apiVersion: v2
kubeVersion: ">=1.23.0-0"
name: slskd
description: A modern client-server application for the Soulseek file sharing network
type: application
version: 0.2.0
appVersion: "0.24.3"
maintainers:
  - name: AlexMorbo
    email: alex@morbo.ru
sources:
  - https://github.com/alexmorbo/helm-charts/tree/master/charts/slskd
icon: https://raw.githubusercontent.com/alexmorbo/helm-charts/refs/heads/master/docs/assets/logo.svg
home: https://github.com/alexmorbo/helm-charts
keywords:
  - slskd
  - soulseek
  - p2p
  - music
  - file-sharing
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/slskd/slskd
    - name: Chart Source
      url: https://github.com/alexmorbo/helm-charts/tree/master/charts/slskd
  artifacthub.io/images: |
    - name: slskd
      image: slskd/slskd:0.24.3
