{{- $createApiKeySecret := not .Values.app.auth.existingSecret }}
{{- $createDbSecret := and .Values.app.database.host .Values.app.database.password (not .Values.app.database.existingSecret) }}
{{- if or $createApiKeySecret $createDbSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lidarr.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lidarr.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if $createApiKeySecret }}
  api-key: {{ include "lidarr.apiKey" . | b64enc | quote }}
  {{- end }}
  {{- if $createDbSecret }}
  db-password: {{ .Values.app.database.password | b64enc | quote }}
  {{- end }}
{{- end }}
