{{- if and .Values.youtubeCookies.enabled (not .Values.youtubeCookies.existingSecret) .Values.youtubeCookies.content }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lidarr.fullname" . }}-youtube-cookies
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lidarr.labels" . | nindent 4 }}
type: Opaque
stringData:
  cookies.txt: |
    {{- .Values.youtubeCookies.content | nindent 4 }}
{{- end }}
