{{- if .Values.route.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "tubearchivist.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tubearchivist.labels" . | nindent 4 }}
    {{- with .Values.route.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- toYaml .Values.route.parentRefs | nindent 4 }}
  hostnames:
    {{- toYaml .Values.route.hostnames | nindent 4 }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "tubearchivist.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
