{{- if and .Values.persistence.media.enabled (not .Values.persistence.media.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tubearchivist.fullname" . }}-media
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tubearchivist.labels" . | nindent 4 }}
  {{- with .Values.persistence.media.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.media.accessModes | nindent 4 }}
  {{- if .Values.persistence.media.storageClass }}
  storageClassName: {{ .Values.persistence.media.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.media.size | quote }}
{{- end }}
