apiVersion: v2
kubeVersion: ">=1.23.0-0"
name: flaresolverr
description: FlareSolverr is a proxy server to bypass Cloudflare and DDoS-GUARD protection
type: application
version: 0.1.0
appVersion: "3.4.6"
maintainers:
  - name: AlexMorbo
    email: alex@morbo.ru
sources:
  - https://github.com/alexmorbo/helm-charts/tree/master/charts/flaresolverr
icon: https://raw.githubusercontent.com/FlareSolverr/FlareSolverr/master/resources/flaresolverr_logo.svg
home: https://github.com/alexmorbo/helm-charts
keywords:
  - flaresolverr
  - cloudflare
  - proxy
  - bypass
  - servarr
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/FlareSolverr/FlareSolverr
    - name: Chart Source
      url: https://github.com/alexmorbo/helm-charts/tree/master/charts/flaresolverr
  artifacthub.io/images: |
    - name: flaresolverr
      image: ghcr.io/flaresolverr/flaresolverr:v3.3.21
