{{- if not .Values.app.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slskd.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "slskd.labels" . | nindent 4 }}
type: Opaque
data:
  soulseek-username: {{ .Values.app.soulseek.username | b64enc | quote }}
  soulseek-password: {{ .Values.app.soulseek.password | b64enc | quote }}
  api-key: {{ .Values.app.web.apiKey | default (randAlphaNum 32) | b64enc | quote }}
{{- end }}
