{{- if .Values.paperlessAi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "paperless-ngx.fullname" . }}-ai
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
    app.kubernetes.io/component: ai
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "paperless-ngx.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: ai
{{- end }}
