{{- if .Values.tika.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "paperless-ngx.fullname" . }}-tika
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
    app.kubernetes.io/component: tika
spec:
  replicas: 1
  strategy:
    {{- include "paperless-ngx.strategy" (dict "local" .Values.tika.strategy "global" .Values.global.strategy) | nindent 4 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "paperless-ngx.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: tika
  template:
    metadata:
      labels:
        {{- include "paperless-ngx.labels" . | nindent 8 }}
        app.kubernetes.io/component: tika
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: tika
          image: {{ include "paperless-ngx.imageRegistry" (dict "local" .Values.tika.image.registry "global" .Values.global.imageRegistry "default" "docker.io") }}/{{ .Values.tika.image.repository }}:{{ .Values.tika.image.tag }}
          imagePullPolicy: {{ .Values.tika.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.tika.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /tika
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /tika
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          {{- with .Values.tika.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.tika.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tika.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tika.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
