apiVersion: v2
kubeVersion: ">=1.23.0-0"
name: qbittorrent
description: qbittorrent helm chart for Kubernetes
type: application
version: 1.0.18
appVersion: "4.6.6"
maintainers:
  - name: AlexMorbo
    email: alex@morbo.ru
sources:
  - https://github.com/alexmorbo/helm-charts/tree/master/charts/qbittorrent
icon: https://raw.githubusercontent.com/alexmorbo/helm-charts/refs/heads/master/docs/assets/logo.svg
home: https://github.com/alexmorbo/helm-charts
keywords:
  - qbittorrent
  - bittorrent
  - download
  - torrent
  - torrents
  - media
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/qbittorrent/qBittorrent
    - name: Chart Source
      url: https://github.com/alexmorbo/helm-charts/tree/master/charts/qbittorrent
  artifacthub.io/images: |
    - name: qbittorrent
      image: onedr0p/qbittorrent:4.6.6
    - name: exporter
      image: martabal/qbittorrent-exporter:v1.13.2
    - name: manage
      image: stuffanthings/qbit_manage:v4.1.15
